---

- set_fact:
    type: site
  when: type is not defined

- include_tasks: "{{ type }}.yml"

- include_tasks: database.yml
  when: database is defined

- include_tasks: dns.yml
  when: dns_ip is defined

