---
- name: Get nginx version
  ansible.builtin.shell: set -o pipefail && nginx -v 2>&1 | cut -d/ -f2
  args:
    executable: "{{ default_shell }}"
  register: nginx_version_installed
  changed_when: false

- name: Set nginx version for templates
  ansible.builtin.set_fact:
    # nginx_version_to_use: "{{ '1.18' if nginx_version_installed.stdout is version('1.25', '<') else '1.25' }}"
    nginx_version: "{{ nginx_version_installed.stdout }}"

- name: Set site and nginx version
  ansible.builtin.set_fact:
    create_dir: "{{ create_dir | default(mit_nginx_create_dir | default('true')) }}"
    type: "{{ type | default('site') }}"

- name: Process site / proxy
  ansible.builtin.include_tasks: "{{ type }}.yml"

- name: Process database
  ansible.builtin.include_tasks: database.yml
  when: database is defined

- name: Process dns
  ansible.builtin.include_tasks: dns.yml
  when: dns_ip is defined
