---
- ansible.builtin.set_fact:
    type: site
  when: type is not defined

- ansible.builtin.include_tasks: "{{ type }}.yml"
- ansible.builtin.include_tasks: database.yml
  when: database is defined

- ansible.builtin.include_tasks: dns.yml
  when: dns_ip is defined
