---
- name: Setting defaults (1/2)
  ansible.builtin.set_fact:
    # If MAILTO is defined but empty (MAILTO=""), no mail will be sent.
    crontab_mailto: "{{ crontab_mailto | default('') }}"
    state: "{{ state | default('present') }}"
    update_facls: "{{ update_facls | default(True) }}"
    update_facls_dir: "{{ 'ci' if (htdocslink is defined) else 'htdocs' }}"

- name: Setting defaults (2/2)
  ansible.builtin.set_fact:
    nginx_client_max_body_size: "{{ nginx_client_max_body_size | default(php_fpm_upload_limit | default(false)) }}"
    create_or_remove: "{{ 'Remove' if (state == 'absent') else 'Create' }}"
    file_state_directory: "{{ 'absent' if (state == 'absent') else 'directory' }}"
    zfs_state_dataset: "{{ 'absent' if (state == 'absent') else 'present' }}"

- name: Setting nginx_include_other defaults
  ansible.builtin.set_fact:
    nginx_include_other: true
  when: nginx_include_other_template is defined and nginx_include_other_template

# - debug: var=nginx_client_max_body_size

# Ensure default owner / group / mode (creating user fails without this)
- name: "{{ create_or_remove }} directory /srv/www/{{ site }}" # noqa: name[template]
  ansible.builtin.file:
    path: /srv/www/{{ site }}
    state: "{{ file_state_directory }}"
    mode: "755"
  when: create_dir|default("true") == "true"

- name: "{{ create_or_remove }} zfs dataset for /srv/www/{{ site }}" # noqa: name[template]
  ansible.builtin.zfs:
    name: tank/www/{{ site }}
    state: "{{ zfs_state_dataset }}"
    extra_zfs_properties:
      mountpoint: /srv/www/{{ site }}
  when: create_dir|default("true") == "zfs"

- name: Creating group {{ group }}
  ansible.builtin.group:
    name: "{{ group }}"
    system: true
  when: state!='absent'

- name: Creating user {{ group }}
  ansible.builtin.user:
    name: "{{ group }}"
    group: "{{ group }}"
    home: /srv/www/{{ site }}/htdocs
    create_home: false # avoid skell files
    shell: /bin/false
    system: true
  when: (create_user|default(true)) and (state!='absent')

- name: Adding www-data to group {{ group }}
  ansible.builtin.user:
    name: www-data
    append: true
    groups: "{{ group }}"
  notify: Reload nginx
  when: state!='absent'

- name: Creating deploy dir
  ansible.builtin.file:
    path: /srv/www/{{ site }}/ci
    state: directory
    owner: "{{ group }}"
    group: "{{ group }}"
    mode: "0770"
  when: state!='absent' and htdocslink is defined

- name: Creating link to htdocs
  ansible.builtin.file:
    src: "{{ htdocslink }}"
    dest: /srv/www/{{ site }}/htdocs
    state: link
    owner: "{{ group }}"
    group: "{{ group }}"
    follow: false # avoid error messages if link does not exists yet
    force: true # avoid error messages if link does not exists yet
  when: state!='absent' and htdocslink is defined

- name: Creating /srv/www/{{ site }}/htdocs # noqa: name[template]
  ansible.builtin.file:
    path: /srv/www/{{ site }}/htdocs
    state: directory
    owner: "{{ group }}"
    group: "{{ group }}"
    mode: "0770"
  when: state!='absent' and htdocslink is not defined

- name: Creating /srv/www/{{ site }}/logs # noqa: name[template]
  ansible.builtin.file:
    path: /srv/www/{{ site }}/logs
    state: directory
    owner: root
    group: "{{ group }}"
    mode: "0750"
  when: state!='absent'

- name: Creating /srv/www/{{ site }}/tmp # noqa: name[template]
  ansible.builtin.file:
    path: /srv/www/{{ site }}/tmp/php
    state: directory
    mode: "770"
  when: state!='absent' and php_fpm_upload_limit is defined

- name: Creating /srv/www/{{ site }}/tmp/nginx # noqa: name[template]
  ansible.builtin.file:
    path: /srv/www/{{ site }}/tmp/nginx
    state: directory
    owner: www-data
    group: www-data
    mode: "770"
  when: state!='absent' and php_fpm_upload_limit is defined

- name: Creating /srv/www/{{ site }}/tmp/php # noqa: name[template]
  ansible.builtin.file:
    path: /srv/www/{{ site }}/tmp/php
    state: directory
    owner: "{{ group }}"
    group: "{{ group }}"
    mode: "0770"
  when: state!='absent' and php_fpm_upload_limit is defined

# doesn't work on session, don't know why
# As of Ansible 2.0, this module only supports Linux distributions.
- name: Enable group adm to read /srv/www/{{ site }}/logs via ACL # noqa: name[template]
  acl:
    path: /srv/www/{{ site }}/logs/
    entity: adm
    etype: group
    permissions: rx
    state: present
  when: state!='absent' and ansible_system == 'Linux'

- name: Check deprecated conf.d/ssl-site (without .include)
  ansible.builtin.command: ls {{ etc_prefix }}/etc/nginx/conf.d/ssl-{{ site }}
  register: cmd_ls
  failed_when: cmd_ls.rc == 0
  changed_when: false

- name: Create {{ etc_prefix }}/etc/nginx/conf.d/server-{{ site }}.conf # noqa: name[template]
  ansible.builtin.template:
    src: nginx-server-template.conf
    dest: "{{ etc_prefix }}/etc/nginx/conf.d/server-{{ site }}.conf"
    force: "{{ nginx_overwrite_config | default('no') }}"
    mode: "644"
  notify: Reload nginx
  when: state!='absent'

- name: Remove {{ etc_prefix }}/etc/nginx/conf.d/server-{{ site }}.conf # noqa: name[template]
  ansible.builtin.file:
    dest: "{{ etc_prefix }}/etc/nginx/conf.d/server-{{ site }}.conf"
    state: absent
  notify: Reload nginx
  when: state=='absent'

# Add nginx_include_other_template if needed

- name: Create {{ etc_prefix }}/etc/nginx/conf.d/server-{{ site }}.include # noqa: name[template]
  ansible.builtin.template:
    src: "{{ nginx_include_other }}"
    dest: "{{ etc_prefix }}/etc/nginx/conf.d/server-{{ site }}.include"
    force: false
    mode: "644"
  when: >
    nginx_include_other|default(false)
    and nginx_include_other != 'True'
    and state!='absent'

- name: Remove {{ etc_prefix }}/etc/nginx/conf.d/server-{{ site }}.include # noqa: name[template]
  ansible.builtin.file:
    dest: "{{ etc_prefix }}/etc/nginx/conf.d/server-{{ site }}.include"
    state: absent
  notify: Reload nginx
  when: state=='absent'

- name: Create {{ etc_prefix }}/etc/nginx/conf.d/server-{{ site }}.htpasswd # noqa: name[template]
  ansible.builtin.copy:
    content: ""
    dest: "{{ etc_prefix }}/etc/nginx/conf.d/server-{{ site }}.htpasswd"
    force: false
    group: www-data
    mode: "0640"
  when: (nginx_create_htpasswd|default(false) or nginx_include_auth_basic|default(false)) and state!='absent'

- name: Remove {{ etc_prefix }}/etc/nginx/conf.d/server-{{ site }}.htpasswd # noqa: name[template]
  ansible.builtin.file:
    dest: "{{ etc_prefix }}/etc/nginx/conf.d/server-{{ site }}.htpasswd"
    state: absent
  when: state=='absent'

- name: Check if there is a pool running on a different php version than {{ php_version }}
  ansible.builtin.shell: set -o pipefail && ls /etc/php/*/fpm/pool.d/{{ site }}.conf|cut -d/ -f4|grep -v {{ php_version }}
  register: cmd_ls_pool
  changed_when: false
  failed_when: cmd_ls_pool.stdout
  when: state!='absent' and php_version is defined

- name: Create /etc/php/{{ php_version }}/fpm/pool.d/{{ site }}.conf # noqa: name[template]
  ansible.builtin.template:
    src: php-fpm-pool-template.conf
    dest: /etc/php/{{ php_version }}/fpm/pool.d/{{ site }}.conf
    force: "{{ php_fpm_overwrite_config | default('no') }}"
    mode: "644"
  notify: Reload php{{ php_version }}-fpm
  when: state!='absent' and php_version is defined

- name: Remove /etc/php/{{ php_version }}/fpm/pool.d/{{ site }}.conf # noqa: name[template]
  ansible.builtin.file:
    dest: /etc/php/{{ php_version }}/fpm/pool.d/{{ site }}.conf
    state: absent
  notify: Reload php{{ php_version }}-fpm
  when: state=='absent'

- name: Update /etc/update-facls.conf
  ansible.builtin.lineinfile:
    path: /etc/update-facls.conf
    regexp: ^/srv/www/{{ site }}/{{ update_facls_dir }}
    line: /srv/www/{{ site }}/{{ update_facls_dir }} {{ group }} {{ group }}
    state: "{{ state }}"
  when: update_facls

- name: Allow execution of service commands via sudo
  ansible.builtin.template:
    src: etc/sudoers.d/local-group
    dest: /etc/sudoers.d/local-group-{{ group }}
    mode: "0440"
    validate: visudo -cf %s
  when: (create_sudoers|default(true)) and (state!='absent')

- name: Remove sudoers file
  ansible.builtin.file:
    dest: /etc/sudoers.d/local-group-{{ group }}
    state: absent
  when: state=='absent'

- name: Redirect mail to {{ group }} to /dev/null # noqa: name[template]
  ansible.builtin.lineinfile:
    path: /etc/aliases
    regexp: "^{{ group }}: "
    line: "{{ group }}: /dev/null"
  notify: newaliases
  when: typo3_bin is defined

# https://docs.typo3.org/c/typo3/cms-scheduler/main/en-us//Installation/CronJob/Index.html
- name: Set TYPO3_CONTEXT environment variable for cron
  ansible.builtin.set_fact:
    # Adds a space at the end
    typo3_context_for_cron: "{{ 'TYPO3_CONTEXT=' + typo3_context + ' ' if typo3_context is defined else '' }}"

- name: Set MAILTO in crontab
  ansible.builtin.cron:
    env: true
    name: MAILTO
    job: "{{ crontab_mailto }}"
    user: "{{ group }}"
  when: crontab_mailto is defined

- name: Install typo3 cronjob
  ansible.builtin.cron:
    user: "{{ group }}"
    name: typo3 Scheduler by meissner.IT
    minute: "*/15"
    job: "{{ typo3_context_for_cron }}php{{ php_version }} /srv/www/{{ site }}/{{ typo3_bin }} scheduler:run"
  when: typo3_bin is defined

# https://docs.ansible.com/ansible/latest/user_guide/playbooks_handlers.html#controlling-when-handlers-run
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
- name: Remove user {{ group }}
  ansible.builtin.user:
    name: "{{ group }}"
    state: absent
  when: state=='absent'

- name: Remove group {{ group }}
  ansible.builtin.group:
    name: "{{ group }}"
    state: absent
  when: state=='absent'

- name: Check fstab entries
  ansible.builtin.command: grep -q {{ site }} /etc/fstab
  register: grep_fstab
  failed_when: grep_fstab.rc == 0
  changed_when: false
  when: state=='absent'
